package rules;

import com.example.bookstorebackend.book.Book;
import com.example.bookstorebackend.person.model.Author
import com.example.bookstorebackend.rating.model.Rating;
import com.example.bookstorebackend.genre.Genre;
import java.util.List;
import java.util.stream.Collectors
import java.util.Comparator
import java.util.ArrayList
import java.util.Collections;
import com.example.bookstorebackend.person.model.User
import com.example.bookstorebackend.person.model.Person
import com.example.bookstorebackend.book.BookCharacteristics
import com.example.bookstorebackend.book.BookForRecommendation;

global java.util.ArrayList recommendedBooks;
global com.example.bookstorebackend.person.model.User specificUser;

rule "Remove Authors Without Books"
salience 30
no-loop true
when
    $author: Author(getBookNumber() == 0)
then
    delete($author);
end

rule "Determine Author Genres"
lock-on-active
salience 25
when
    $author: Author()
    $genres: List(size > 0) from collect(Genre())
then
    boolean valid = false;
    for(Object genre: $genres){
        int count = $author.getBookNumberFromGenre((Genre)genre);
        if((count * 1.0 / $author.getBooks().size()) > 0.3){
            valid = true;
        }
    }
    if(valid){
        modify($author){setCorrectGenre(valid)}
    }
end

rule "Collect All Authors"
salience 20
no-loop true
when
    $authors: List(size > 0) from collect(Author(isCorrectGenre() == true))
then
    List<Author> authors = new ArrayList<>($authors);
    authors.sort(Comparator.comparingDouble(a -> ((Author)a).getTotalRatingNumber()).reversed());
    List<Author> sublist = authors.subList(0, Math.min(authors.size(), 4));
    for(Object c: $authors){
        delete(c);
    }
    for(Author author: sublist){
        author.setPopular(true);
        insert(author);
    }
end

rule "Insert Books From Popular Authors"
salience 15
no-loop true
when
  $author: Author(isPopular() == true)
then
    for(Book book: $author.getBooks()) {
        insert(book);
    }
end

rule "Select Top 10 Books"
salience 10
no-loop true
when
  $books: List(size > 0) from collect(Book())
  $user: User(id == specificUser.getId() && getRatingsNumber() < 10)
then
    System.out.println("Rule [Select Top 10 Books] - fired");
    List<Book> sortedBooks = new ArrayList<>($books);
    sortedBooks.sort(Comparator.comparingDouble(a -> ((Book)a).getTotalRatingNumber()).reversed());
    List<Book> top10Books = sortedBooks.subList(0, Math.min(sortedBooks.size(), 10));
    recommendedBooks.addAll(top10Books);
end

rule "Users similarity based on Pearson correlation coefficient"
salience 5
no-loop true
when
    $user: User(id == specificUser.getId() && getRatingsNumber() >= 10)
    $user2: User(id != specificUser.getId())
    $books: List(size > 0) from collect(Book())
then
        System.out.println("Rule [Users similarity based on Pearson correlation coefficient] - fired");
        double similarity = $user.calculateSimilarity($user2);
        if (similarity >= 0.5) {
            List<String> booksLikedBySimilarUser = $user2.getRatings().stream()
                .filter(rating -> rating.getRating() >= 4.0)
                .map(rating -> rating.getBook().getId().toString())
                .collect(Collectors.toList());
            List<Book> allBooks = new ArrayList<>($books);
            List<Book> booksLikedByUser = new ArrayList<>();
            for (String bookId : booksLikedBySimilarUser) {
                for(Book book : allBooks){
                    if(book.getId() == Long.parseLong(bookId)){
                        booksLikedByUser.add(book);
                    }
                }
                }
            recommendedBooks.addAll(booksLikedByUser);
        }
end

rule "Add points to books that are similar to books that user likes"
when
    $user: User(id == specificUser.getId() && getRatingsNumber() >= 10)
    $otherUser: User(id != specificUser.getId())
    $thisBook: Book(id != 0)
    $books: List() from $user.getBooksThatUserLikes()
then
    List<BookForRecommendation> booksList = new ArrayList<>();
    for (var otherBook: $books) {
        if ($thisBook.areBooksSimilar((Book)otherBook)) {
            booksList.add(new BookForRecommendation((Book)otherBook, 1));
        }
    }
end