package rules.booksNonauthenticated;

import com.example.bookstorebackend.book.*;
import java.time.LocalDate;

rule "Book test"
    when
        $b: Book(price > 1000)
    then
        System.out.println($b.getPublisher());
end;

rule "Book is new if it's added to bookstore in last 1 month"
    activation-group "book characteristics"
    no-loop true
    when
        $bc: BookCharacteristics(book.dateOfAddingToBookstore > LocalDate.now().minusMonths(1))
    then
        System.out.println("Rule [Book is new if it's added to bookstore in last 1 month] - fired");
        modify($bc){ setNew(true) }
end;

rule "Book is new if it's published to bookstore in last 6 month"
    activation-group "book characteristics"
    no-loop true
    when
        $bc: BookCharacteristics(book.publishDate > LocalDate.now().minusMonths(6))
    then
        System.out.println("Rule [Book is new if it's published to bookstore in last 6 month] - fired");
        modify($bc){ setNew(true) }
end;

rule "Suggest book if it's new"
    activation-group "suggestions"
    salience -1
    when
        $bc: BookCharacteristics(isNew() == true)
    then
        System.out.println("Rule [Suggest book if it's new] - fired");
        modify($bc) { setSuggested(true) }
end;